<div class="form">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
        <h4 class="modal-title" id="addModalLabel">新建一次性任务</h4>
    </div>
    <div class="modal-body">
        <form id="app-form">
            <div class="form-group input-group  input-control">
                <span class="input-group-addon">项目名称&nbsp;</span>
                <input type="text" class="form-control" id="app_name" name="app_name"  post-name="app_name" placeholder="如rds" notnull>
            </div>
            <div class="form-group input-group  input-control">
                <span class="input-group-addon">执行命令&nbsp;</span>
                <input type="text" class="form-control" id="command" name="command"  post-name="command" placeholder="" notnull>
            </div>
            <div class="form-group input-group  input-control">
                <span class="input-group-addon">任务说明</span>
                <input type="text" class="form-control" id="note" name="note" post-name="note" placeholder="">
            </div>
            <div class="form-group input-group  input-control">
                <span class="input-group-addon">失败重试<a href="#"  id="tip"  class="btn-sm" rel="popover" data-content="在任务失败时系统会自动重新调度一次此任务 启用此选项时请确认任务多次执行的结果幂等" data-original-title="">?</a></span>
                <select name="force"  post-name="retry" id="retry"  class="form-control">
                    <option value="0" selected>否</option>
                    <option value="1">是</option>
                </select>

            </div>
        </form>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">&nbsp;&nbsp;取消&nbsp;&nbsp;</button>
        <button type="button" class="btn btn-primary submit" post="<?=APP_ADMIN_PATH?>/job/addonce" success="success">&nbsp;&nbsp;保存&nbsp;&nbsp;</button>
    </div>
</div>

<script>
    $(function (){
        $("#tip").popover();
    });
    function success() {
        var app_name = $('#app_name').val();
        window.location.href = "<?=APP_ADMIN_PATH?>/job/once?app_name="+app_name;
    }
</script>