<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>一次性任务管理</title>
    <?php include(APPLICATION_BASE_TPL_PATH . "/inc/include.phtml"); ?>
    <style>
        .sortable img {width:96px;height:86px;border:1px solid #aeaeae;padding:1px;}
        .sortable div { margin: 3px 3px 3px 0; padding: 1px; float: left; width: 100px; height: 90px; font-size: 4em; text-align: center; }
    </style>

</head>
<body>
<div id="wrapper">
    <?php echo $menuview; ?>
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <ul class="breadcrumb">
                    <li>
                        <span class="glyphicon glyphicon-user"></span><a href="#">一次性任务管理</a>
                    </li>
                </ul>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <div class="row">
            <div class="panel panel-default">
                <div class="panel-heading search-panel">
                    <div class="panel-body" style="height: 50px">
                        <input type="text" class="form-control" id="search_app_name" name="search_app_name" placeholder="请输入需要查询的项目名" value="<?=$app_name?>" style="width: 250px">
                        <button type="button" class="btn btn-primary btn-lg right add-top" onclick="javascript:openDialog('Modal', url('/job/addonceview'));" style="margin-top: -40px">&nbsp;&nbsp;&nbsp;添加任务&nbsp;&nbsp;&nbsp;</button>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.row -->
        <div class="row"><div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="table-responsive">
                                <table class="table" id="dataTables-admin">
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /#page-wrapper -->
            <!-- Modal -->
            <script>

                var $_GET = (function(){
                    var url = window.document.location.href.toString();
                    var u = url.split("?");
                    if(typeof(u[1]) == "string"){
                        u = u[1].split("&");
                        var get = {};
                        for(var i in u){
                            var j = u[i].split("=");
                            get[j[0]] = j[1];
                        }
                        return get;
                    } else {
                        return {};
                    }
                })();

                $(document).ready(function () {
                    $('#dataTables-admin').dataTable({
                        serverSide: true,
                        "columns": [
                            { "title": "ID", "data": "id"},
                            { "title": "项目名", "data": "app_name",'visible':false},
                            { "title": "执行命令", "data": "command"},
                            { "title": "说明", "data": "note"},
                            { "title": "失败重试", "data": "retry",render:function(data,type,row){
                                if(data == 0){
                                    return "否";
                                }else if(data == 1){
                                    return "是";
                                }
                            }},
                            { "title": "状态", "data": "status",render:function(data,type,row){
                                if(data == 0){
                                    return "等待调度";
                                }else if(data == 1){
                                    return "调度成功";
                                }
                            }},
                            { "title": "申请人", "data": "proposer"},
                            { "title": "创建时间", "data": "ctime"},
                            { "title": "操作", data: "status", render: function(data, type, row){
                                buttonString = "<button type='button' class='btn btn_operate btn-debug see-log'>日志</button>";
                                if(data == 0){
                                    buttonString +=  "<button type='button' class='btn btn_operate btn-warning to_force'>强制调度</button>";
                                    return buttonString;
                                }
                                return buttonString;
                            }}
                         ],
                        'ajax' : '<?=APP_ADMIN_PATH?>/job/oncetable',
                        "iDisplayLength":20,
                        "ordering":false
                    });
                    // 筛选服务
                    $('#search_app_name').blur(function(){
                        var app_name = $(this).val();
                        var url = '<?=APP_ADMIN_PATH?>/job/once?app_name='+app_name;
                        jumpUrl(url)
                    });

                    $(document).on('click', '.to_force', function(){
                        ret = confirm("请确认是否强制调度该任务?\n[机器在负载高的情况下会延迟调度一次性任务]");
                        if(ret){
                            var id = $(this).parent().prev().prev().prev().prev().prev().prev().text();
                            var app_name = $_GET['app_name'];

                            $.post("<?=APP_ADMIN_PATH?>/job/setonceforce", {
                                id : id
                            }, function(ret){
                                if (ret.retcode == "2000000") {
                                    var table = $('#dataTables-admin').dataTable().api();
                                    var url = '<?=APP_ADMIN_PATH?>/job/oncetable?app_name='+app_name;
                                    table.ajax.url(url).load();
                                    alert(ret.msg);
                                }
                            }, "json")
                        }
                    });

                    $(document).on('click', '.see-log', function(){
                        var id = $(this).parent().prev().prev().prev().prev().prev().prev().prev().text();
                        log_list = "<?=APP_ADMIN_PATH?>/job/log?job_id="+id+"&type=1";
                        jumpUrl(log_list);
                    });

                    if($_GET['app_name']){
                        var app_name = $_GET['app_name'];
                        var table = $('#dataTables-admin').dataTable().api();
                        var url = '<?=APP_ADMIN_PATH?>/job/oncetable?app_name='+app_name;
                        table.ajax.url(url).load();
                    }

                });

            </script>
</body>
</html>
